server:
  port: 8080
  servlet:
    session:
      timeout: 86400

spring:
  profiles:
    include: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${ip}/badminton?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Y

  redis:
    host: ${ip}
    port: 6379
    database: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.model
  configuration:
    map-underscore-to-camel-case: true

ip: 172.20.58.211

logging:
  level:
    com:
      example:
        demo:
          mapper: DEBUG
    org:
      apache:
        ibatis:
          executor:
            BaseExecutor: DEBUG
